name = "JuliaDevTemplates"
uuid = "3b99f05d-ae1a-4c1c-b7d3-e16963076e64"
authors = ["Andy Liang"]
version = "0.1.0"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
